version: '3.8'

services:
  frontend:
    image: intergalactictrash/rags-frontend
    build: ./ui
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: intergalactictrash/rags-backend
    build: ./llm
    ports:
      - "8000:8000"
    volumes:
      - /home/austin/rag_data:/app/rag_data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
